---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiger-trade-bot-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  # uncomment or set based on your cluster
