---
apiVersion: v1
kind: Service
metadata:
  name: tiger-trade-bot
  labels:
    app: tiger-trade-bot
spec:
  selector:
    app: tiger-trade-bot
  ports:
  - name: health
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
